# Generated by Django 3.1.4 on 2021-02-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210123_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='id_user',
            field=models.IntegerField(default=1, verbose_name='Пользователь'),
        ),
    ]
