# Generated by Django 3.1.4 on 2021-02-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articles_id_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
