# Generated by Django 3.1.4 on 2021-02-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='my_photo',
            field=models.FileField(upload_to='Images'),
        ),
    ]
