# Generated by Django 3.1.4 on 2021-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210221_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='my_photo',
            field=models.FileField(upload_to=''),
        ),
    ]
