# Generated by Django 3.1.4 on 2021-02-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20210221_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='my_photo',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
