# Generated by Django 3.1.4 on 2021-01-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(default='admin', max_length=15, verbose_name='Пароль'),
        ),
    ]
