# Generated by Django 3.1.4 on 2021-01-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_registration_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('password', models.CharField(default='admin', max_length=15, verbose_name='Пароль')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('date', models.DateTimeField(verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Регистрация2',
                'verbose_name_plural': 'Регистрации2',
            },
        ),
    ]
